### ISSUE TITLE
New Select/Autocomplete/Search component

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1025]
Issue to track development of new Select/Autocomplete Component

> We should also look into merging any search functionality into this. Then we can deprecate `TsSearch`

- [x] Replace `TsSelect` (target 10.0)
- [x] Deprecate `TsAutocomplete` (target 11.0)
- [ ] Deprecate `TsSearch` (target 11.0)

---

### High-level feature set

- [x] Works with ngModel
- [x] Works with FormControl
- [x] Floating label
- [x] Single or multiple select
- [x] Full element can be disabled
- [x] Individual option can be disabled
- [x] Seed initial value (using form control or ngModel)
- [x] ~Formatter for UI~
- [x] ~Formatter for model~
- [ ] **Moving to fast-follow** Ability to create a new item that wasn't originally in the list
  - Open question: how to handle two use-cases:
    - a) User can add a new option to an existing list. Each item needs to be saved or rejected from the consumer.
    - b) User can define list of options which are saved all at once at the end (eg standard form submission)
- [x] Event emitters
- [x] Categorized options in dropdown (optgroup)
  - [x] An optgroup in multiple mode should be able to select/deselect all enabled optgroup children.
- [x] Theme support
- [x] Debounce search (autocomplete)
  - [x] custom debounce time (default to 200)
- [x] Minimum character count (autocomplete)
  - [x] custom char count (default to 3)
- [x] Query is only sent if string is unique (autocomplete)
  - [x] add flag to allow duplicate queries
- [x] ~Show error for duplicate selection (autocomplete)~ handled by consumer now
- [x] ~Mark as touched if opened and closed with no selection~ currently not needed
- [x] Mark required if attr or form validation exists (`hasRequiredControl`)
- [x] Validation message support
- [x] Hint support
- [x] Chips can be removed via UI
- [x] Token separators: `,`
- [x] ~Ability to clear **single** select (`x` on right like search component)~
  - This will be handled via a 'blank option' choice to better follow native select elements.
- [x] Dropdown appears below input
  - [x] Exception: If a value is selected, that value is vertically centered in the select when opened. If multiple values are selected, the first selection is centered vertically.
- [x] Options that are longer than the input should truncate to not break layout.
- [x] Options should have tooltips with the full value to allow users to see truncated options.
- [x] Ability to show progress for long queries
- [x] Allow custom option template to be used. Component will pass `option` to the template. This should allow for full customization on the UI.
  - [x] If no template passed in, it should use a default template that matches the existing format/style.
- [x] Should allow blank option
- [ ] TBD: Selects with many options by default show a single option that says 'load all options'
- [ ] Figure out what to do about the select display when in pagination. I'd like to remove legacy styling support.
- [x] Consumer should be able to use custom DOM for the select trigger.
- [x] Selecting/deselecting all options should be a single click for a user.
  - [x] Disabled options should not be toggled
- [x] Dropdown should support keyboard navigation and keyboard selection
- [x] Should have checkboxes to control when in multiple mode
  - [x] Checkboxes should not appear when in autocomplete mode
- [x] Panel should have flag to keep it open after selections when in multiple mode.

---

#### Example usage

```html
<!-- custom option template -->
<ts-select>
  <ts-select-option>
    <img [src]="option.logo" height="25">
    <span>{{ option.name }}</span> |
    <small>{{ option.description }}</small>
  </ts-select-option>
</ts-select>
```

---

#### Resources

- https://moduscreate.com/blog/adding-keyboard-navigation-to-angular-lists-using-angular-cdk-listkeymanager/
- https://sketch.cloud/s/xgx3J
- https://material.angular.io/cdk/portal/overview
- https://blog.angularindepth.com/how-do-cdk-portals-work-7c097c14a494
- https://github.com/angular/material2/blob/master/src/lib/select/select.ts
- `@import '~@angular/cdk/overlay-prebuilt.css';`
- https://juristr.com/blog/2018/05/dynamic-UI-with-cdk-portals/

**Comment by benjamincharity** [comment]
Also fixing https://github.com/GetTerminus/terminus-ui/issues/1061
