### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1182]
Add release notes about:

- [x] Angular upgrade
- [x] TypeScript upgrade
- [x] Any other lib upgrades
- [x] Boolean coercion deprecation
- [x] Material now peer dependency
- [x] CSV default format
- [x] Remove duplicate validation messages
- [x] Multiple entry points / test helpers
