### ISSUE TITLE
v12

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1364]
- [x] Create new `v12` branch
- [x] Create `11.x.x` branch for legacy
  - [x] Update release etc for this branch
- [x] Create v11 github pages repo
  - `git@github.com:GetTerminus/ui-demos-11.x.x.git`
- [ ] Add new legacy branch to primary docs
