### ISSUE TITLE
TsSelectionList: New component

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1632]
This component will be replacing both `TsSelect` and `TsAutocomplete`.

### Requirements

- [x] Name `ts-selection-list` - `TsSelectionListComponent`
- [x] Must support dropdown arrow
  - Should become visible automatically at least one option exists
  - Icon: `arrow_drop_down`
- [x] Must support complex objects for values AND chip values
    - Enforce model/view with interface that expects `value` and `display`. `TsListSelectionItem`
- [x] Only drops down - ie no panel positioning madness
- [x] When focused and options exist, it should open the panel
- [x] Should close if clicking anywhere else - even onto another Autocomplete (currently we're matching on node name so clicking another autocomplete doesn't close one that is already open)
- [ ] Should use `ts-chips-collection` internally for multiple mode

### Todo

- [x] Clone the existing `TsAutocomplete` code for the starting point
- [ ] Update any uses of `TsSelect` or `TsAutocomplete` within other components (ie pagination)
- [ ] Update any uses of `TsSelect` or `TsAutocomplete` within the demo (ie demo selector)
- [ ] Deprecate `TsSelect` & `TsAutocomplete`
- [ ] Add demo page and demos
- [ ] Add JSDoc and Usage docs
- [ ] Add tests

**Comment by deanterm** [comment]
Just a note on this, there is a bug in the autocomplete component that if you have more than 1 autocomplete on a page, and you switch from the 1st autocomplete to the second, the options panel doesn't close. You have to click anywhere else but the autocomplete input to get the panel to close before clicking into the other autocomplete input.

So, when cloning the autocomplete, please fix this or the end of the world will be upon us.

**Comment by benjamincharity** [comment]
Yup, it's listed in the requirements 👍

**Comment by deanterm** [comment]
doh, I didn't see that. muh bad
