### ISSUE TITLE
Create visual regression tests

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#2042]
We should be thoughtful about setting up regression tests much like unit tests: we should avoid double testing where possible (eg login form doesn't need to test button styles since the button will test that itself, but it should test the basic layout)

### Components that should be tested visually

- [ ] button
- [ ] card
- [ ] checkbox
- [ ] chip
- [ ] cohort date range (mainly layout)
- [ ] confirmation
- [ ] copy
- [ ] csv entry
- [ ] date range (mainly layout)
- [ ] drawer
- [ ] expansion panel
- [ ] file upload
- [ ] icon
- [ ] icon button
- [ ] input
- [ ] link
- [ ] loading overlay
- [ ] login form (mainly layout)
- [ ] logo
- [ ] menu
- [ ] navigation
- [ ] paginator
- [ ] popover
- [ ] radio group
- [ ] scrollbars
- [ ] search (mainly layout)
- [ ] selection list
- [ ] spacing
- [ ] table
- [ ] tabs
- [ ] toggle
- [ ] tooltip

TODO: Create individual tickets for each item and attach to this epic.
